<?php

/**
 * Base class that represents a row from the 'projectes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Oct 19 11:38:06 2009
 *
 * @package    lib.model.om
 */
abstract class BaseProjectes extends BaseObject  implements Persistent {


  const PEER = 'ProjectesPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProjectesPeer
	 */
	protected static $peer;

	/**
	 * The value for the idprojectes field.
	 * @var        int
	 */
	protected $idprojectes;

	/**
	 * The value for the entitats_entitatid field.
	 * @var        int
	 */
	protected $entitats_entitatid;

	/**
	 * The value for the nom field.
	 * @var        string
	 */
	protected $nom;

	/**
	 * The value for the descripcio field.
	 * @var        string
	 */
	protected $descripcio;

	/**
	 * The value for the habilitat field.
	 * @var        int
	 */
	protected $habilitat;

	/**
	 * @var        Entitats
	 */
	protected $aEntitats;

	/**
	 * @var        array ProjectesHasAgendaactivitats[] Collection to store aggregation of ProjectesHasAgendaactivitats objects.
	 */
	protected $collProjectesHasAgendaactivitatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProjectesHasAgendaactivitatss.
	 */
	private $lastProjectesHasAgendaactivitatsCriteria = null;

	/**
	 * @var        array ProjectesHasBlogarticles[] Collection to store aggregation of ProjectesHasBlogarticles objects.
	 */
	protected $collProjectesHasBlogarticless;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProjectesHasBlogarticless.
	 */
	private $lastProjectesHasBlogarticlesCriteria = null;

	/**
	 * @var        array SubcategoriesHasProjectes[] Collection to store aggregation of SubcategoriesHasProjectes objects.
	 */
	protected $collSubcategoriesHasProjectess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSubcategoriesHasProjectess.
	 */
	private $lastSubcategoriesHasProjectesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseProjectes object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [idprojectes] column value.
	 * 
	 * @return     int
	 */
	public function getIdprojectes()
	{
		return $this->idprojectes;
	}

	/**
	 * Get the [entitats_entitatid] column value.
	 * 
	 * @return     int
	 */
	public function getEntitatsEntitatid()
	{
		return $this->entitats_entitatid;
	}

	/**
	 * Get the [nom] column value.
	 * 
	 * @return     string
	 */
	public function getNom()
	{
		return $this->nom;
	}

	/**
	 * Get the [descripcio] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcio()
	{
		return $this->descripcio;
	}

	/**
	 * Get the [habilitat] column value.
	 * 
	 * @return     int
	 */
	public function getHabilitat()
	{
		return $this->habilitat;
	}

	/**
	 * Set the value of [idprojectes] column.
	 * 
	 * @param      int $v new value
	 * @return     Projectes The current object (for fluent API support)
	 */
	public function setIdprojectes($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idprojectes !== $v) {
			$this->idprojectes = $v;
			$this->modifiedColumns[] = ProjectesPeer::IDPROJECTES;
		}

		return $this;
	} // setIdprojectes()

	/**
	 * Set the value of [entitats_entitatid] column.
	 * 
	 * @param      int $v new value
	 * @return     Projectes The current object (for fluent API support)
	 */
	public function setEntitatsEntitatid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->entitats_entitatid !== $v) {
			$this->entitats_entitatid = $v;
			$this->modifiedColumns[] = ProjectesPeer::ENTITATS_ENTITATID;
		}

		if ($this->aEntitats !== null && $this->aEntitats->getEntitatid() !== $v) {
			$this->aEntitats = null;
		}

		return $this;
	} // setEntitatsEntitatid()

	/**
	 * Set the value of [nom] column.
	 * 
	 * @param      string $v new value
	 * @return     Projectes The current object (for fluent API support)
	 */
	public function setNom($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nom !== $v) {
			$this->nom = $v;
			$this->modifiedColumns[] = ProjectesPeer::NOM;
		}

		return $this;
	} // setNom()

	/**
	 * Set the value of [descripcio] column.
	 * 
	 * @param      string $v new value
	 * @return     Projectes The current object (for fluent API support)
	 */
	public function setDescripcio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcio !== $v) {
			$this->descripcio = $v;
			$this->modifiedColumns[] = ProjectesPeer::DESCRIPCIO;
		}

		return $this;
	} // setDescripcio()

	/**
	 * Set the value of [habilitat] column.
	 * 
	 * @param      int $v new value
	 * @return     Projectes The current object (for fluent API support)
	 */
	public function setHabilitat($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->habilitat !== $v) {
			$this->habilitat = $v;
			$this->modifiedColumns[] = ProjectesPeer::HABILITAT;
		}

		return $this;
	} // setHabilitat()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->idprojectes = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->entitats_entitatid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nom = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->descripcio = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->habilitat = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = ProjectesPeer::NUM_COLUMNS - ProjectesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Projectes object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEntitats !== null && $this->entitats_entitatid !== $this->aEntitats->getEntitatid()) {
			$this->aEntitats = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProjectesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ProjectesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEntitats = null;
			$this->collProjectesHasAgendaactivitatss = null;
			$this->lastProjectesHasAgendaactivitatsCriteria = null;

			$this->collProjectesHasBlogarticless = null;
			$this->lastProjectesHasBlogarticlesCriteria = null;

			$this->collSubcategoriesHasProjectess = null;
			$this->lastSubcategoriesHasProjectesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProjectes:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProjectesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ProjectesPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseProjectes:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProjectes:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProjectesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseProjectes:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ProjectesPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEntitats !== null) {
				if ($this->aEntitats->isModified() || $this->aEntitats->isNew()) {
					$affectedRows += $this->aEntitats->save($con);
				}
				$this->setEntitats($this->aEntitats);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ProjectesPeer::IDPROJECTES;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProjectesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdprojectes($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProjectesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collProjectesHasAgendaactivitatss !== null) {
				foreach ($this->collProjectesHasAgendaactivitatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProjectesHasBlogarticless !== null) {
				foreach ($this->collProjectesHasBlogarticless as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSubcategoriesHasProjectess !== null) {
				foreach ($this->collSubcategoriesHasProjectess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEntitats !== null) {
				if (!$this->aEntitats->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEntitats->getValidationFailures());
				}
			}


			if (($retval = ProjectesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collProjectesHasAgendaactivitatss !== null) {
					foreach ($this->collProjectesHasAgendaactivitatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProjectesHasBlogarticless !== null) {
					foreach ($this->collProjectesHasBlogarticless as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSubcategoriesHasProjectess !== null) {
					foreach ($this->collSubcategoriesHasProjectess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProjectesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdprojectes();
				break;
			case 1:
				return $this->getEntitatsEntitatid();
				break;
			case 2:
				return $this->getNom();
				break;
			case 3:
				return $this->getDescripcio();
				break;
			case 4:
				return $this->getHabilitat();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ProjectesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdprojectes(),
			$keys[1] => $this->getEntitatsEntitatid(),
			$keys[2] => $this->getNom(),
			$keys[3] => $this->getDescripcio(),
			$keys[4] => $this->getHabilitat(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProjectesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdprojectes($value);
				break;
			case 1:
				$this->setEntitatsEntitatid($value);
				break;
			case 2:
				$this->setNom($value);
				break;
			case 3:
				$this->setDescripcio($value);
				break;
			case 4:
				$this->setHabilitat($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ProjectesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdprojectes($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setEntitatsEntitatid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNom($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescripcio($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setHabilitat($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProjectesPeer::IDPROJECTES)) $criteria->add(ProjectesPeer::IDPROJECTES, $this->idprojectes);
		if ($this->isColumnModified(ProjectesPeer::ENTITATS_ENTITATID)) $criteria->add(ProjectesPeer::ENTITATS_ENTITATID, $this->entitats_entitatid);
		if ($this->isColumnModified(ProjectesPeer::NOM)) $criteria->add(ProjectesPeer::NOM, $this->nom);
		if ($this->isColumnModified(ProjectesPeer::DESCRIPCIO)) $criteria->add(ProjectesPeer::DESCRIPCIO, $this->descripcio);
		if ($this->isColumnModified(ProjectesPeer::HABILITAT)) $criteria->add(ProjectesPeer::HABILITAT, $this->habilitat);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);

		$criteria->add(ProjectesPeer::IDPROJECTES, $this->idprojectes);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdprojectes();
	}

	/**
	 * Generic method to set the primary key (idprojectes column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdprojectes($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Projectes (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setEntitatsEntitatid($this->entitats_entitatid);

		$copyObj->setNom($this->nom);

		$copyObj->setDescripcio($this->descripcio);

		$copyObj->setHabilitat($this->habilitat);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getProjectesHasAgendaactivitatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProjectesHasAgendaactivitats($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getProjectesHasBlogarticless() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProjectesHasBlogarticles($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSubcategoriesHasProjectess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSubcategoriesHasProjectes($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdprojectes(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Projectes Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProjectesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProjectesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Entitats object.
	 *
	 * @param      Entitats $v
	 * @return     Projectes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEntitats(Entitats $v = null)
	{
		if ($v === null) {
			$this->setEntitatsEntitatid(NULL);
		} else {
			$this->setEntitatsEntitatid($v->getEntitatid());
		}

		$this->aEntitats = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Entitats object, it will not be re-added.
		if ($v !== null) {
			$v->addProjectes($this);
		}

		return $this;
	}


	/**
	 * Get the associated Entitats object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Entitats The associated Entitats object.
	 * @throws     PropelException
	 */
	public function getEntitats(PropelPDO $con = null)
	{
		if ($this->aEntitats === null && ($this->entitats_entitatid !== null)) {
			$c = new Criteria(EntitatsPeer::DATABASE_NAME);
			$c->add(EntitatsPeer::ENTITATID, $this->entitats_entitatid);
			$this->aEntitats = EntitatsPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEntitats->addProjectess($this);
			 */
		}
		return $this->aEntitats;
	}

	/**
	 * Clears out the collProjectesHasAgendaactivitatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProjectesHasAgendaactivitatss()
	 */
	public function clearProjectesHasAgendaactivitatss()
	{
		$this->collProjectesHasAgendaactivitatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProjectesHasAgendaactivitatss collection (array).
	 *
	 * By default this just sets the collProjectesHasAgendaactivitatss collection to an empty array (like clearcollProjectesHasAgendaactivitatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProjectesHasAgendaactivitatss()
	{
		$this->collProjectesHasAgendaactivitatss = array();
	}

	/**
	 * Gets an array of ProjectesHasAgendaactivitats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Projectes has previously been saved, it will retrieve
	 * related ProjectesHasAgendaactivitatss from storage. If this Projectes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProjectesHasAgendaactivitats[]
	 * @throws     PropelException
	 */
	public function getProjectesHasAgendaactivitatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
			   $this->collProjectesHasAgendaactivitatss = array();
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				ProjectesHasAgendaactivitatsPeer::addSelectColumns($criteria);
				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				ProjectesHasAgendaactivitatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
					$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProjectesHasAgendaactivitatsCriteria = $criteria;
		return $this->collProjectesHasAgendaactivitatss;
	}

	/**
	 * Returns the number of related ProjectesHasAgendaactivitats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProjectesHasAgendaactivitats objects.
	 * @throws     PropelException
	 */
	public function countProjectesHasAgendaactivitatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$count = ProjectesHasAgendaactivitatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
					$count = ProjectesHasAgendaactivitatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProjectesHasAgendaactivitatss);
				}
			} else {
				$count = count($this->collProjectesHasAgendaactivitatss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProjectesHasAgendaactivitats object to this object
	 * through the ProjectesHasAgendaactivitats foreign key attribute.
	 *
	 * @param      ProjectesHasAgendaactivitats $l ProjectesHasAgendaactivitats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProjectesHasAgendaactivitats(ProjectesHasAgendaactivitats $l)
	{
		if ($this->collProjectesHasAgendaactivitatss === null) {
			$this->initProjectesHasAgendaactivitatss();
		}
		if (!in_array($l, $this->collProjectesHasAgendaactivitatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProjectesHasAgendaactivitatss, $l);
			$l->setProjectes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Projectes is new, it will return
	 * an empty collection; or if this Projectes has previously
	 * been saved, it will retrieve related ProjectesHasAgendaactivitatss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Projectes.
	 */
	public function getProjectesHasAgendaactivitatssJoinAgendaactivitats($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
				$this->collProjectesHasAgendaactivitatss = array();
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelectJoinAgendaactivitats($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProjectesHasAgendaactivitatsPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

			if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelectJoinAgendaactivitats($criteria, $con, $join_behavior);
			}
		}
		$this->lastProjectesHasAgendaactivitatsCriteria = $criteria;

		return $this->collProjectesHasAgendaactivitatss;
	}

	/**
	 * Clears out the collProjectesHasBlogarticless collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProjectesHasBlogarticless()
	 */
	public function clearProjectesHasBlogarticless()
	{
		$this->collProjectesHasBlogarticless = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProjectesHasBlogarticless collection (array).
	 *
	 * By default this just sets the collProjectesHasBlogarticless collection to an empty array (like clearcollProjectesHasBlogarticless());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProjectesHasBlogarticless()
	{
		$this->collProjectesHasBlogarticless = array();
	}

	/**
	 * Gets an array of ProjectesHasBlogarticles objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Projectes has previously been saved, it will retrieve
	 * related ProjectesHasBlogarticless from storage. If this Projectes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProjectesHasBlogarticles[]
	 * @throws     PropelException
	 */
	public function getProjectesHasBlogarticless($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasBlogarticless === null) {
			if ($this->isNew()) {
			   $this->collProjectesHasBlogarticless = array();
			} else {

				$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				ProjectesHasBlogarticlesPeer::addSelectColumns($criteria);
				$this->collProjectesHasBlogarticless = ProjectesHasBlogarticlesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				ProjectesHasBlogarticlesPeer::addSelectColumns($criteria);
				if (!isset($this->lastProjectesHasBlogarticlesCriteria) || !$this->lastProjectesHasBlogarticlesCriteria->equals($criteria)) {
					$this->collProjectesHasBlogarticless = ProjectesHasBlogarticlesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProjectesHasBlogarticlesCriteria = $criteria;
		return $this->collProjectesHasBlogarticless;
	}

	/**
	 * Returns the number of related ProjectesHasBlogarticles objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProjectesHasBlogarticles objects.
	 * @throws     PropelException
	 */
	public function countProjectesHasBlogarticless(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProjectesHasBlogarticless === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$count = ProjectesHasBlogarticlesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				if (!isset($this->lastProjectesHasBlogarticlesCriteria) || !$this->lastProjectesHasBlogarticlesCriteria->equals($criteria)) {
					$count = ProjectesHasBlogarticlesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProjectesHasBlogarticless);
				}
			} else {
				$count = count($this->collProjectesHasBlogarticless);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProjectesHasBlogarticles object to this object
	 * through the ProjectesHasBlogarticles foreign key attribute.
	 *
	 * @param      ProjectesHasBlogarticles $l ProjectesHasBlogarticles
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProjectesHasBlogarticles(ProjectesHasBlogarticles $l)
	{
		if ($this->collProjectesHasBlogarticless === null) {
			$this->initProjectesHasBlogarticless();
		}
		if (!in_array($l, $this->collProjectesHasBlogarticless, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProjectesHasBlogarticless, $l);
			$l->setProjectes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Projectes is new, it will return
	 * an empty collection; or if this Projectes has previously
	 * been saved, it will retrieve related ProjectesHasBlogarticless from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Projectes.
	 */
	public function getProjectesHasBlogarticlessJoinBlogarticles($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasBlogarticless === null) {
			if ($this->isNew()) {
				$this->collProjectesHasBlogarticless = array();
			} else {

				$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$this->collProjectesHasBlogarticless = ProjectesHasBlogarticlesPeer::doSelectJoinBlogarticles($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProjectesHasBlogarticlesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

			if (!isset($this->lastProjectesHasBlogarticlesCriteria) || !$this->lastProjectesHasBlogarticlesCriteria->equals($criteria)) {
				$this->collProjectesHasBlogarticless = ProjectesHasBlogarticlesPeer::doSelectJoinBlogarticles($criteria, $con, $join_behavior);
			}
		}
		$this->lastProjectesHasBlogarticlesCriteria = $criteria;

		return $this->collProjectesHasBlogarticless;
	}

	/**
	 * Clears out the collSubcategoriesHasProjectess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSubcategoriesHasProjectess()
	 */
	public function clearSubcategoriesHasProjectess()
	{
		$this->collSubcategoriesHasProjectess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSubcategoriesHasProjectess collection (array).
	 *
	 * By default this just sets the collSubcategoriesHasProjectess collection to an empty array (like clearcollSubcategoriesHasProjectess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSubcategoriesHasProjectess()
	{
		$this->collSubcategoriesHasProjectess = array();
	}

	/**
	 * Gets an array of SubcategoriesHasProjectes objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Projectes has previously been saved, it will retrieve
	 * related SubcategoriesHasProjectess from storage. If this Projectes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SubcategoriesHasProjectes[]
	 * @throws     PropelException
	 */
	public function getSubcategoriesHasProjectess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubcategoriesHasProjectess === null) {
			if ($this->isNew()) {
			   $this->collSubcategoriesHasProjectess = array();
			} else {

				$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				SubcategoriesHasProjectesPeer::addSelectColumns($criteria);
				$this->collSubcategoriesHasProjectess = SubcategoriesHasProjectesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				SubcategoriesHasProjectesPeer::addSelectColumns($criteria);
				if (!isset($this->lastSubcategoriesHasProjectesCriteria) || !$this->lastSubcategoriesHasProjectesCriteria->equals($criteria)) {
					$this->collSubcategoriesHasProjectess = SubcategoriesHasProjectesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSubcategoriesHasProjectesCriteria = $criteria;
		return $this->collSubcategoriesHasProjectess;
	}

	/**
	 * Returns the number of related SubcategoriesHasProjectes objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SubcategoriesHasProjectes objects.
	 * @throws     PropelException
	 */
	public function countSubcategoriesHasProjectess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSubcategoriesHasProjectess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$count = SubcategoriesHasProjectesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				if (!isset($this->lastSubcategoriesHasProjectesCriteria) || !$this->lastSubcategoriesHasProjectesCriteria->equals($criteria)) {
					$count = SubcategoriesHasProjectesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collSubcategoriesHasProjectess);
				}
			} else {
				$count = count($this->collSubcategoriesHasProjectess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SubcategoriesHasProjectes object to this object
	 * through the SubcategoriesHasProjectes foreign key attribute.
	 *
	 * @param      SubcategoriesHasProjectes $l SubcategoriesHasProjectes
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSubcategoriesHasProjectes(SubcategoriesHasProjectes $l)
	{
		if ($this->collSubcategoriesHasProjectess === null) {
			$this->initSubcategoriesHasProjectess();
		}
		if (!in_array($l, $this->collSubcategoriesHasProjectess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSubcategoriesHasProjectess, $l);
			$l->setProjectes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Projectes is new, it will return
	 * an empty collection; or if this Projectes has previously
	 * been saved, it will retrieve related SubcategoriesHasProjectess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Projectes.
	 */
	public function getSubcategoriesHasProjectessJoinSubcategories($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProjectesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubcategoriesHasProjectess === null) {
			if ($this->isNew()) {
				$this->collSubcategoriesHasProjectess = array();
			} else {

				$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

				$this->collSubcategoriesHasProjectess = SubcategoriesHasProjectesPeer::doSelectJoinSubcategories($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SubcategoriesHasProjectesPeer::PROJECTES_IDPROJECTES, $this->idprojectes);

			if (!isset($this->lastSubcategoriesHasProjectesCriteria) || !$this->lastSubcategoriesHasProjectesCriteria->equals($criteria)) {
				$this->collSubcategoriesHasProjectess = SubcategoriesHasProjectesPeer::doSelectJoinSubcategories($criteria, $con, $join_behavior);
			}
		}
		$this->lastSubcategoriesHasProjectesCriteria = $criteria;

		return $this->collSubcategoriesHasProjectess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collProjectesHasAgendaactivitatss) {
				foreach ((array) $this->collProjectesHasAgendaactivitatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collProjectesHasBlogarticless) {
				foreach ((array) $this->collProjectesHasBlogarticless as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSubcategoriesHasProjectess) {
				foreach ((array) $this->collSubcategoriesHasProjectess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collProjectesHasAgendaactivitatss = null;
		$this->collProjectesHasBlogarticless = null;
		$this->collSubcategoriesHasProjectess = null;
			$this->aEntitats = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseProjectes:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseProjectes::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseProjectes
