<?php

/**
 * Base class that represents a row from the 'agendaactivitats' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Sep  1 14:15:02 2009
 *
 * @package    lib.model.om
 */
abstract class BaseAgendaactivitats extends BaseObject  implements Persistent {


  const PEER = 'AgendaactivitatsPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AgendaactivitatsPeer
	 */
	protected static $peer;

	/**
	 * The value for the agendaactivitatsactivitatsid field.
	 * @var        int
	 */
	protected $agendaactivitatsactivitatsid;

	/**
	 * The value for the cluber_idclubber field.
	 * @var        int
	 */
	protected $cluber_idclubber;

	/**
	 * The value for the titol field.
	 * @var        string
	 */
	protected $titol;

	/**
	 * The value for the text field.
	 * @var        string
	 */
	protected $text;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the lloc field.
	 * @var        string
	 */
	protected $lloc;

	/**
	 * The value for the horai field.
	 * @var        string
	 */
	protected $horai;

	/**
	 * The value for the horaf field.
	 * @var        string
	 */
	protected $horaf;

	/**
	 * The value for the link field.
	 * @var        string
	 */
	protected $link;

	/**
	 * The value for the ciutat field.
	 * @var        string
	 */
	protected $ciutat;

	/**
	 * @var        Cluber
	 */
	protected $aCluber;

	/**
	 * @var        array ProjectesHasAgendaactivitats[] Collection to store aggregation of ProjectesHasAgendaactivitats objects.
	 */
	protected $collProjectesHasAgendaactivitatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProjectesHasAgendaactivitatss.
	 */
	private $lastProjectesHasAgendaactivitatsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAgendaactivitats object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [agendaactivitatsactivitatsid] column value.
	 * 
	 * @return     int
	 */
	public function getAgendaactivitatsactivitatsid()
	{
		return $this->agendaactivitatsactivitatsid;
	}

	/**
	 * Get the [cluber_idclubber] column value.
	 * 
	 * @return     int
	 */
	public function getCluberIdclubber()
	{
		return $this->cluber_idclubber;
	}

	/**
	 * Get the [titol] column value.
	 * 
	 * @return     string
	 */
	public function getTitol()
	{
		return $this->titol;
	}

	/**
	 * Get the [text] column value.
	 * 
	 * @return     string
	 */
	public function getText()
	{
		return $this->text;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [lloc] column value.
	 * 
	 * @return     string
	 */
	public function getLloc()
	{
		return $this->lloc;
	}

	/**
	 * Get the [optionally formatted] temporal [horai] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getHorai($format = 'H:i:s')
	{
		if ($this->horai === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->horai);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->horai, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [horaf] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getHoraf($format = 'H:i:s')
	{
		if ($this->horaf === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->horaf);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->horaf, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [link] column value.
	 * 
	 * @return     string
	 */
	public function getLink()
	{
		return $this->link;
	}

	/**
	 * Get the [ciutat] column value.
	 * 
	 * @return     string
	 */
	public function getCiutat()
	{
		return $this->ciutat;
	}

	/**
	 * Set the value of [agendaactivitatsactivitatsid] column.
	 * 
	 * @param      int $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setAgendaactivitatsactivitatsid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->agendaactivitatsactivitatsid !== $v) {
			$this->agendaactivitatsactivitatsid = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::AGENDAACTIVITATSACTIVITATSID;
		}

		return $this;
	} // setAgendaactivitatsactivitatsid()

	/**
	 * Set the value of [cluber_idclubber] column.
	 * 
	 * @param      int $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setCluberIdclubber($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cluber_idclubber !== $v) {
			$this->cluber_idclubber = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::CLUBER_IDCLUBBER;
		}

		if ($this->aCluber !== null && $this->aCluber->getIdclubber() !== $v) {
			$this->aCluber = null;
		}

		return $this;
	} // setCluberIdclubber()

	/**
	 * Set the value of [titol] column.
	 * 
	 * @param      string $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setTitol($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titol !== $v) {
			$this->titol = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::TITOL;
		}

		return $this;
	} // setTitol()

	/**
	 * Set the value of [text] column.
	 * 
	 * @param      string $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setText($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->text !== $v) {
			$this->text = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::TEXT;
		}

		return $this;
	} // setText()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AgendaactivitatsPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [lloc] column.
	 * 
	 * @param      string $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setLloc($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lloc !== $v) {
			$this->lloc = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::LLOC;
		}

		return $this;
	} // setLloc()

	/**
	 * Sets the value of [horai] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setHorai($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->horai !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->horai !== null && $tmpDt = new DateTime($this->horai)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->horai = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = AgendaactivitatsPeer::HORAI;
			}
		} // if either are not null

		return $this;
	} // setHorai()

	/**
	 * Sets the value of [horaf] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setHoraf($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->horaf !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->horaf !== null && $tmpDt = new DateTime($this->horaf)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->horaf = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = AgendaactivitatsPeer::HORAF;
			}
		} // if either are not null

		return $this;
	} // setHoraf()

	/**
	 * Set the value of [link] column.
	 * 
	 * @param      string $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setLink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->link !== $v) {
			$this->link = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::LINK;
		}

		return $this;
	} // setLink()

	/**
	 * Set the value of [ciutat] column.
	 * 
	 * @param      string $v new value
	 * @return     Agendaactivitats The current object (for fluent API support)
	 */
	public function setCiutat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ciutat !== $v) {
			$this->ciutat = $v;
			$this->modifiedColumns[] = AgendaactivitatsPeer::CIUTAT;
		}

		return $this;
	} // setCiutat()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->agendaactivitatsactivitatsid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->cluber_idclubber = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->titol = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->text = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->date = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->lloc = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->horai = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->horaf = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->link = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ciutat = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = AgendaactivitatsPeer::NUM_COLUMNS - AgendaactivitatsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Agendaactivitats object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCluber !== null && $this->cluber_idclubber !== $this->aCluber->getIdclubber()) {
			$this->aCluber = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgendaactivitatsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AgendaactivitatsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCluber = null;
			$this->collProjectesHasAgendaactivitatss = null;
			$this->lastProjectesHasAgendaactivitatsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgendaactivitats:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgendaactivitatsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AgendaactivitatsPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAgendaactivitats:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgendaactivitats:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgendaactivitatsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAgendaactivitats:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AgendaactivitatsPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCluber !== null) {
				if ($this->aCluber->isModified() || $this->aCluber->isNew()) {
					$affectedRows += $this->aCluber->save($con);
				}
				$this->setCluber($this->aCluber);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AgendaactivitatsPeer::AGENDAACTIVITATSACTIVITATSID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AgendaactivitatsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setAgendaactivitatsactivitatsid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AgendaactivitatsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collProjectesHasAgendaactivitatss !== null) {
				foreach ($this->collProjectesHasAgendaactivitatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCluber !== null) {
				if (!$this->aCluber->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCluber->getValidationFailures());
				}
			}


			if (($retval = AgendaactivitatsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collProjectesHasAgendaactivitatss !== null) {
					foreach ($this->collProjectesHasAgendaactivitatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgendaactivitatsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getAgendaactivitatsactivitatsid();
				break;
			case 1:
				return $this->getCluberIdclubber();
				break;
			case 2:
				return $this->getTitol();
				break;
			case 3:
				return $this->getText();
				break;
			case 4:
				return $this->getDate();
				break;
			case 5:
				return $this->getLloc();
				break;
			case 6:
				return $this->getHorai();
				break;
			case 7:
				return $this->getHoraf();
				break;
			case 8:
				return $this->getLink();
				break;
			case 9:
				return $this->getCiutat();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AgendaactivitatsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getAgendaactivitatsactivitatsid(),
			$keys[1] => $this->getCluberIdclubber(),
			$keys[2] => $this->getTitol(),
			$keys[3] => $this->getText(),
			$keys[4] => $this->getDate(),
			$keys[5] => $this->getLloc(),
			$keys[6] => $this->getHorai(),
			$keys[7] => $this->getHoraf(),
			$keys[8] => $this->getLink(),
			$keys[9] => $this->getCiutat(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgendaactivitatsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setAgendaactivitatsactivitatsid($value);
				break;
			case 1:
				$this->setCluberIdclubber($value);
				break;
			case 2:
				$this->setTitol($value);
				break;
			case 3:
				$this->setText($value);
				break;
			case 4:
				$this->setDate($value);
				break;
			case 5:
				$this->setLloc($value);
				break;
			case 6:
				$this->setHorai($value);
				break;
			case 7:
				$this->setHoraf($value);
				break;
			case 8:
				$this->setLink($value);
				break;
			case 9:
				$this->setCiutat($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AgendaactivitatsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setAgendaactivitatsactivitatsid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCluberIdclubber($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitol($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setText($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDate($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLloc($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHorai($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setHoraf($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setLink($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCiutat($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AgendaactivitatsPeer::DATABASE_NAME);

		if ($this->isColumnModified(AgendaactivitatsPeer::AGENDAACTIVITATSACTIVITATSID)) $criteria->add(AgendaactivitatsPeer::AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);
		if ($this->isColumnModified(AgendaactivitatsPeer::CLUBER_IDCLUBBER)) $criteria->add(AgendaactivitatsPeer::CLUBER_IDCLUBBER, $this->cluber_idclubber);
		if ($this->isColumnModified(AgendaactivitatsPeer::TITOL)) $criteria->add(AgendaactivitatsPeer::TITOL, $this->titol);
		if ($this->isColumnModified(AgendaactivitatsPeer::TEXT)) $criteria->add(AgendaactivitatsPeer::TEXT, $this->text);
		if ($this->isColumnModified(AgendaactivitatsPeer::DATE)) $criteria->add(AgendaactivitatsPeer::DATE, $this->date);
		if ($this->isColumnModified(AgendaactivitatsPeer::LLOC)) $criteria->add(AgendaactivitatsPeer::LLOC, $this->lloc);
		if ($this->isColumnModified(AgendaactivitatsPeer::HORAI)) $criteria->add(AgendaactivitatsPeer::HORAI, $this->horai);
		if ($this->isColumnModified(AgendaactivitatsPeer::HORAF)) $criteria->add(AgendaactivitatsPeer::HORAF, $this->horaf);
		if ($this->isColumnModified(AgendaactivitatsPeer::LINK)) $criteria->add(AgendaactivitatsPeer::LINK, $this->link);
		if ($this->isColumnModified(AgendaactivitatsPeer::CIUTAT)) $criteria->add(AgendaactivitatsPeer::CIUTAT, $this->ciutat);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AgendaactivitatsPeer::DATABASE_NAME);

		$criteria->add(AgendaactivitatsPeer::AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getAgendaactivitatsactivitatsid();
	}

	/**
	 * Generic method to set the primary key (agendaactivitatsactivitatsid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setAgendaactivitatsactivitatsid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Agendaactivitats (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCluberIdclubber($this->cluber_idclubber);

		$copyObj->setTitol($this->titol);

		$copyObj->setText($this->text);

		$copyObj->setDate($this->date);

		$copyObj->setLloc($this->lloc);

		$copyObj->setHorai($this->horai);

		$copyObj->setHoraf($this->horaf);

		$copyObj->setLink($this->link);

		$copyObj->setCiutat($this->ciutat);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getProjectesHasAgendaactivitatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProjectesHasAgendaactivitats($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setAgendaactivitatsactivitatsid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Agendaactivitats Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AgendaactivitatsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AgendaactivitatsPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Cluber object.
	 *
	 * @param      Cluber $v
	 * @return     Agendaactivitats The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCluber(Cluber $v = null)
	{
		if ($v === null) {
			$this->setCluberIdclubber(NULL);
		} else {
			$this->setCluberIdclubber($v->getIdclubber());
		}

		$this->aCluber = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cluber object, it will not be re-added.
		if ($v !== null) {
			$v->addAgendaactivitats($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cluber object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cluber The associated Cluber object.
	 * @throws     PropelException
	 */
	public function getCluber(PropelPDO $con = null)
	{
		if ($this->aCluber === null && ($this->cluber_idclubber !== null)) {
			$c = new Criteria(CluberPeer::DATABASE_NAME);
			$c->add(CluberPeer::IDCLUBBER, $this->cluber_idclubber);
			$this->aCluber = CluberPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCluber->addAgendaactivitatss($this);
			 */
		}
		return $this->aCluber;
	}

	/**
	 * Clears out the collProjectesHasAgendaactivitatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProjectesHasAgendaactivitatss()
	 */
	public function clearProjectesHasAgendaactivitatss()
	{
		$this->collProjectesHasAgendaactivitatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProjectesHasAgendaactivitatss collection (array).
	 *
	 * By default this just sets the collProjectesHasAgendaactivitatss collection to an empty array (like clearcollProjectesHasAgendaactivitatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProjectesHasAgendaactivitatss()
	{
		$this->collProjectesHasAgendaactivitatss = array();
	}

	/**
	 * Gets an array of ProjectesHasAgendaactivitats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Agendaactivitats has previously been saved, it will retrieve
	 * related ProjectesHasAgendaactivitatss from storage. If this Agendaactivitats is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProjectesHasAgendaactivitats[]
	 * @throws     PropelException
	 */
	public function getProjectesHasAgendaactivitatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgendaactivitatsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
			   $this->collProjectesHasAgendaactivitatss = array();
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

				ProjectesHasAgendaactivitatsPeer::addSelectColumns($criteria);
				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

				ProjectesHasAgendaactivitatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
					$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProjectesHasAgendaactivitatsCriteria = $criteria;
		return $this->collProjectesHasAgendaactivitatss;
	}

	/**
	 * Returns the number of related ProjectesHasAgendaactivitats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProjectesHasAgendaactivitats objects.
	 * @throws     PropelException
	 */
	public function countProjectesHasAgendaactivitatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgendaactivitatsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

				$count = ProjectesHasAgendaactivitatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

				if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
					$count = ProjectesHasAgendaactivitatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProjectesHasAgendaactivitatss);
				}
			} else {
				$count = count($this->collProjectesHasAgendaactivitatss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProjectesHasAgendaactivitats object to this object
	 * through the ProjectesHasAgendaactivitats foreign key attribute.
	 *
	 * @param      ProjectesHasAgendaactivitats $l ProjectesHasAgendaactivitats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProjectesHasAgendaactivitats(ProjectesHasAgendaactivitats $l)
	{
		if ($this->collProjectesHasAgendaactivitatss === null) {
			$this->initProjectesHasAgendaactivitatss();
		}
		if (!in_array($l, $this->collProjectesHasAgendaactivitatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProjectesHasAgendaactivitatss, $l);
			$l->setAgendaactivitats($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Agendaactivitats is new, it will return
	 * an empty collection; or if this Agendaactivitats has previously
	 * been saved, it will retrieve related ProjectesHasAgendaactivitatss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Agendaactivitats.
	 */
	public function getProjectesHasAgendaactivitatssJoinProjectes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgendaactivitatsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProjectesHasAgendaactivitatss === null) {
			if ($this->isNew()) {
				$this->collProjectesHasAgendaactivitatss = array();
			} else {

				$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelectJoinProjectes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProjectesHasAgendaactivitatsPeer::AGENDAACTIVITATS_AGENDAACTIVITATSACTIVITATSID, $this->agendaactivitatsactivitatsid);

			if (!isset($this->lastProjectesHasAgendaactivitatsCriteria) || !$this->lastProjectesHasAgendaactivitatsCriteria->equals($criteria)) {
				$this->collProjectesHasAgendaactivitatss = ProjectesHasAgendaactivitatsPeer::doSelectJoinProjectes($criteria, $con, $join_behavior);
			}
		}
		$this->lastProjectesHasAgendaactivitatsCriteria = $criteria;

		return $this->collProjectesHasAgendaactivitatss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collProjectesHasAgendaactivitatss) {
				foreach ((array) $this->collProjectesHasAgendaactivitatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collProjectesHasAgendaactivitatss = null;
			$this->aCluber = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAgendaactivitats:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAgendaactivitats::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAgendaactivitats
