<?php

/**
 * Base class that represents a row from the 'fitxerscomentaris' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Nov 25 14:28:58 2009
 *
 * @package    lib.model.om
 */
abstract class BaseFitxerscomentaris extends BaseObject  implements Persistent {


  const PEER = 'FitxerscomentarisPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FitxerscomentarisPeer
	 */
	protected static $peer;

	/**
	 * The value for the idfitxerscomentaris field.
	 * @var        int
	 */
	protected $idfitxerscomentaris;

	/**
	 * The value for the usuaris_idusuari field.
	 * @var        int
	 */
	protected $usuaris_idusuari;

	/**
	 * The value for the fitxers_fitxersid field.
	 * @var        int
	 */
	protected $fitxers_fitxersid;

	/**
	 * The value for the comentari field.
	 * @var        string
	 */
	protected $comentari;

	/**
	 * @var        Usuaris
	 */
	protected $aUsuaris;

	/**
	 * @var        Fitxers
	 */
	protected $aFitxers;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseFitxerscomentaris object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [idfitxerscomentaris] column value.
	 * 
	 * @return     int
	 */
	public function getIdfitxerscomentaris()
	{
		return $this->idfitxerscomentaris;
	}

	/**
	 * Get the [usuaris_idusuari] column value.
	 * 
	 * @return     int
	 */
	public function getUsuarisIdusuari()
	{
		return $this->usuaris_idusuari;
	}

	/**
	 * Get the [fitxers_fitxersid] column value.
	 * 
	 * @return     int
	 */
	public function getFitxersFitxersid()
	{
		return $this->fitxers_fitxersid;
	}

	/**
	 * Get the [comentari] column value.
	 * 
	 * @return     string
	 */
	public function getComentari()
	{
		return $this->comentari;
	}

	/**
	 * Set the value of [idfitxerscomentaris] column.
	 * 
	 * @param      int $v new value
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 */
	public function setIdfitxerscomentaris($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idfitxerscomentaris !== $v) {
			$this->idfitxerscomentaris = $v;
			$this->modifiedColumns[] = FitxerscomentarisPeer::IDFITXERSCOMENTARIS;
		}

		return $this;
	} // setIdfitxerscomentaris()

	/**
	 * Set the value of [usuaris_idusuari] column.
	 * 
	 * @param      int $v new value
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 */
	public function setUsuarisIdusuari($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuaris_idusuari !== $v) {
			$this->usuaris_idusuari = $v;
			$this->modifiedColumns[] = FitxerscomentarisPeer::USUARIS_IDUSUARI;
		}

		if ($this->aUsuaris !== null && $this->aUsuaris->getUsuariid() !== $v) {
			$this->aUsuaris = null;
		}

		return $this;
	} // setUsuarisIdusuari()

	/**
	 * Set the value of [fitxers_fitxersid] column.
	 * 
	 * @param      int $v new value
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 */
	public function setFitxersFitxersid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fitxers_fitxersid !== $v) {
			$this->fitxers_fitxersid = $v;
			$this->modifiedColumns[] = FitxerscomentarisPeer::FITXERS_FITXERSID;
		}

		if ($this->aFitxers !== null && $this->aFitxers->getFitxersid() !== $v) {
			$this->aFitxers = null;
		}

		return $this;
	} // setFitxersFitxersid()

	/**
	 * Set the value of [comentari] column.
	 * 
	 * @param      string $v new value
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 */
	public function setComentari($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comentari !== $v) {
			$this->comentari = $v;
			$this->modifiedColumns[] = FitxerscomentarisPeer::COMENTARI;
		}

		return $this;
	} // setComentari()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->idfitxerscomentaris = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->usuaris_idusuari = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->fitxers_fitxersid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->comentari = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = FitxerscomentarisPeer::NUM_COLUMNS - FitxerscomentarisPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Fitxerscomentaris object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuaris !== null && $this->usuaris_idusuari !== $this->aUsuaris->getUsuariid()) {
			$this->aUsuaris = null;
		}
		if ($this->aFitxers !== null && $this->fitxers_fitxersid !== $this->aFitxers->getFitxersid()) {
			$this->aFitxers = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FitxerscomentarisPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FitxerscomentarisPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsuaris = null;
			$this->aFitxers = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFitxerscomentaris:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FitxerscomentarisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			FitxerscomentarisPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseFitxerscomentaris:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFitxerscomentaris:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FitxerscomentarisPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseFitxerscomentaris:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			FitxerscomentarisPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuaris !== null) {
				if ($this->aUsuaris->isModified() || $this->aUsuaris->isNew()) {
					$affectedRows += $this->aUsuaris->save($con);
				}
				$this->setUsuaris($this->aUsuaris);
			}

			if ($this->aFitxers !== null) {
				if ($this->aFitxers->isModified() || $this->aFitxers->isNew()) {
					$affectedRows += $this->aFitxers->save($con);
				}
				$this->setFitxers($this->aFitxers);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FitxerscomentarisPeer::IDFITXERSCOMENTARIS;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FitxerscomentarisPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdfitxerscomentaris($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FitxerscomentarisPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuaris !== null) {
				if (!$this->aUsuaris->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuaris->getValidationFailures());
				}
			}

			if ($this->aFitxers !== null) {
				if (!$this->aFitxers->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFitxers->getValidationFailures());
				}
			}


			if (($retval = FitxerscomentarisPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FitxerscomentarisPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdfitxerscomentaris();
				break;
			case 1:
				return $this->getUsuarisIdusuari();
				break;
			case 2:
				return $this->getFitxersFitxersid();
				break;
			case 3:
				return $this->getComentari();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FitxerscomentarisPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdfitxerscomentaris(),
			$keys[1] => $this->getUsuarisIdusuari(),
			$keys[2] => $this->getFitxersFitxersid(),
			$keys[3] => $this->getComentari(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FitxerscomentarisPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdfitxerscomentaris($value);
				break;
			case 1:
				$this->setUsuarisIdusuari($value);
				break;
			case 2:
				$this->setFitxersFitxersid($value);
				break;
			case 3:
				$this->setComentari($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FitxerscomentarisPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdfitxerscomentaris($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsuarisIdusuari($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFitxersFitxersid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setComentari($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FitxerscomentarisPeer::DATABASE_NAME);

		if ($this->isColumnModified(FitxerscomentarisPeer::IDFITXERSCOMENTARIS)) $criteria->add(FitxerscomentarisPeer::IDFITXERSCOMENTARIS, $this->idfitxerscomentaris);
		if ($this->isColumnModified(FitxerscomentarisPeer::USUARIS_IDUSUARI)) $criteria->add(FitxerscomentarisPeer::USUARIS_IDUSUARI, $this->usuaris_idusuari);
		if ($this->isColumnModified(FitxerscomentarisPeer::FITXERS_FITXERSID)) $criteria->add(FitxerscomentarisPeer::FITXERS_FITXERSID, $this->fitxers_fitxersid);
		if ($this->isColumnModified(FitxerscomentarisPeer::COMENTARI)) $criteria->add(FitxerscomentarisPeer::COMENTARI, $this->comentari);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FitxerscomentarisPeer::DATABASE_NAME);

		$criteria->add(FitxerscomentarisPeer::IDFITXERSCOMENTARIS, $this->idfitxerscomentaris);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdfitxerscomentaris();
	}

	/**
	 * Generic method to set the primary key (idfitxerscomentaris column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdfitxerscomentaris($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Fitxerscomentaris (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsuarisIdusuari($this->usuaris_idusuari);

		$copyObj->setFitxersFitxersid($this->fitxers_fitxersid);

		$copyObj->setComentari($this->comentari);


		$copyObj->setNew(true);

		$copyObj->setIdfitxerscomentaris(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Fitxerscomentaris Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FitxerscomentarisPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FitxerscomentarisPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usuaris object.
	 *
	 * @param      Usuaris $v
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuaris(Usuaris $v = null)
	{
		if ($v === null) {
			$this->setUsuarisIdusuari(NULL);
		} else {
			$this->setUsuarisIdusuari($v->getUsuariid());
		}

		$this->aUsuaris = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuaris object, it will not be re-added.
		if ($v !== null) {
			$v->addFitxerscomentaris($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuaris object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuaris The associated Usuaris object.
	 * @throws     PropelException
	 */
	public function getUsuaris(PropelPDO $con = null)
	{
		if ($this->aUsuaris === null && ($this->usuaris_idusuari !== null)) {
			$c = new Criteria(UsuarisPeer::DATABASE_NAME);
			$c->add(UsuarisPeer::USUARIID, $this->usuaris_idusuari);
			$this->aUsuaris = UsuarisPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuaris->addFitxerscomentariss($this);
			 */
		}
		return $this->aUsuaris;
	}

	/**
	 * Declares an association between this object and a Fitxers object.
	 *
	 * @param      Fitxers $v
	 * @return     Fitxerscomentaris The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFitxers(Fitxers $v = null)
	{
		if ($v === null) {
			$this->setFitxersFitxersid(NULL);
		} else {
			$this->setFitxersFitxersid($v->getFitxersid());
		}

		$this->aFitxers = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Fitxers object, it will not be re-added.
		if ($v !== null) {
			$v->addFitxerscomentaris($this);
		}

		return $this;
	}


	/**
	 * Get the associated Fitxers object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Fitxers The associated Fitxers object.
	 * @throws     PropelException
	 */
	public function getFitxers(PropelPDO $con = null)
	{
		if ($this->aFitxers === null && ($this->fitxers_fitxersid !== null)) {
			$c = new Criteria(FitxersPeer::DATABASE_NAME);
			$c->add(FitxersPeer::FITXERSID, $this->fitxers_fitxersid);
			$this->aFitxers = FitxersPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFitxers->addFitxerscomentariss($this);
			 */
		}
		return $this->aFitxers;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aUsuaris = null;
			$this->aFitxers = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseFitxerscomentaris:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseFitxerscomentaris::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseFitxerscomentaris
