<?php

/**
 * Base class that represents a row from the 'cluber' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Oct 19 11:38:05 2009
 *
 * @package    lib.model.om
 */
abstract class BaseCluber extends BaseObject  implements Persistent {


  const PEER = 'CluberPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CluberPeer
	 */
	protected static $peer;

	/**
	 * The value for the idclubber field.
	 * @var        int
	 */
	protected $idclubber;

	/**
	 * The value for the nivells_idnivells field.
	 * @var        int
	 */
	protected $nivells_idnivells;

	/**
	 * The value for the entitats_entitatid field.
	 * @var        int
	 */
	protected $entitats_entitatid;

	/**
	 * The value for the usuaris_usuariid field.
	 * @var        int
	 */
	protected $usuaris_usuariid;

	/**
	 * The value for the habilitat field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $habilitat;

	/**
	 * @var        Nivells
	 */
	protected $aNivells;

	/**
	 * @var        Entitats
	 */
	protected $aEntitats;

	/**
	 * @var        Usuaris
	 */
	protected $aUsuaris;

	/**
	 * @var        array Agendaactivitats[] Collection to store aggregation of Agendaactivitats objects.
	 */
	protected $collAgendaactivitatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgendaactivitatss.
	 */
	private $lastAgendaactivitatsCriteria = null;

	/**
	 * @var        array Blogarticles[] Collection to store aggregation of Blogarticles objects.
	 */
	protected $collBlogarticless;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBlogarticless.
	 */
	private $lastBlogarticlesCriteria = null;

	/**
	 * @var        array Fitxers[] Collection to store aggregation of Fitxers objects.
	 */
	protected $collFitxerss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFitxerss.
	 */
	private $lastFitxersCriteria = null;

	/**
	 * @var        array Fitxerscomentaris[] Collection to store aggregation of Fitxerscomentaris objects.
	 */
	protected $collFitxerscomentariss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFitxerscomentariss.
	 */
	private $lastFitxerscomentarisCriteria = null;

	/**
	 * @var        array Multimedia[] Collection to store aggregation of Multimedia objects.
	 */
	protected $collMultimedias;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMultimedias.
	 */
	private $lastMultimediaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCluber object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->habilitat = 1;
	}

	/**
	 * Get the [idclubber] column value.
	 * 
	 * @return     int
	 */
	public function getIdclubber()
	{
		return $this->idclubber;
	}

	/**
	 * Get the [nivells_idnivells] column value.
	 * 
	 * @return     int
	 */
	public function getNivellsIdnivells()
	{
		return $this->nivells_idnivells;
	}

	/**
	 * Get the [entitats_entitatid] column value.
	 * 
	 * @return     int
	 */
	public function getEntitatsEntitatid()
	{
		return $this->entitats_entitatid;
	}

	/**
	 * Get the [usuaris_usuariid] column value.
	 * 
	 * @return     int
	 */
	public function getUsuarisUsuariid()
	{
		return $this->usuaris_usuariid;
	}

	/**
	 * Get the [habilitat] column value.
	 * 
	 * @return     int
	 */
	public function getHabilitat()
	{
		return $this->habilitat;
	}

	/**
	 * Set the value of [idclubber] column.
	 * 
	 * @param      int $v new value
	 * @return     Cluber The current object (for fluent API support)
	 */
	public function setIdclubber($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->idclubber !== $v) {
			$this->idclubber = $v;
			$this->modifiedColumns[] = CluberPeer::IDCLUBBER;
		}

		return $this;
	} // setIdclubber()

	/**
	 * Set the value of [nivells_idnivells] column.
	 * 
	 * @param      int $v new value
	 * @return     Cluber The current object (for fluent API support)
	 */
	public function setNivellsIdnivells($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nivells_idnivells !== $v) {
			$this->nivells_idnivells = $v;
			$this->modifiedColumns[] = CluberPeer::NIVELLS_IDNIVELLS;
		}

		if ($this->aNivells !== null && $this->aNivells->getIdnivells() !== $v) {
			$this->aNivells = null;
		}

		return $this;
	} // setNivellsIdnivells()

	/**
	 * Set the value of [entitats_entitatid] column.
	 * 
	 * @param      int $v new value
	 * @return     Cluber The current object (for fluent API support)
	 */
	public function setEntitatsEntitatid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->entitats_entitatid !== $v) {
			$this->entitats_entitatid = $v;
			$this->modifiedColumns[] = CluberPeer::ENTITATS_ENTITATID;
		}

		if ($this->aEntitats !== null && $this->aEntitats->getEntitatid() !== $v) {
			$this->aEntitats = null;
		}

		return $this;
	} // setEntitatsEntitatid()

	/**
	 * Set the value of [usuaris_usuariid] column.
	 * 
	 * @param      int $v new value
	 * @return     Cluber The current object (for fluent API support)
	 */
	public function setUsuarisUsuariid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuaris_usuariid !== $v) {
			$this->usuaris_usuariid = $v;
			$this->modifiedColumns[] = CluberPeer::USUARIS_USUARIID;
		}

		if ($this->aUsuaris !== null && $this->aUsuaris->getUsuariid() !== $v) {
			$this->aUsuaris = null;
		}

		return $this;
	} // setUsuarisUsuariid()

	/**
	 * Set the value of [habilitat] column.
	 * 
	 * @param      int $v new value
	 * @return     Cluber The current object (for fluent API support)
	 */
	public function setHabilitat($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->habilitat !== $v || $v === 1) {
			$this->habilitat = $v;
			$this->modifiedColumns[] = CluberPeer::HABILITAT;
		}

		return $this;
	} // setHabilitat()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(CluberPeer::HABILITAT))) {
				return false;
			}

			if ($this->habilitat !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->idclubber = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nivells_idnivells = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->entitats_entitatid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->usuaris_usuariid = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->habilitat = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = CluberPeer::NUM_COLUMNS - CluberPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Cluber object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aNivells !== null && $this->nivells_idnivells !== $this->aNivells->getIdnivells()) {
			$this->aNivells = null;
		}
		if ($this->aEntitats !== null && $this->entitats_entitatid !== $this->aEntitats->getEntitatid()) {
			$this->aEntitats = null;
		}
		if ($this->aUsuaris !== null && $this->usuaris_usuariid !== $this->aUsuaris->getUsuariid()) {
			$this->aUsuaris = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CluberPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CluberPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aNivells = null;
			$this->aEntitats = null;
			$this->aUsuaris = null;
			$this->collAgendaactivitatss = null;
			$this->lastAgendaactivitatsCriteria = null;

			$this->collBlogarticless = null;
			$this->lastBlogarticlesCriteria = null;

			$this->collFitxerss = null;
			$this->lastFitxersCriteria = null;

			$this->collFitxerscomentariss = null;
			$this->lastFitxerscomentarisCriteria = null;

			$this->collMultimedias = null;
			$this->lastMultimediaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCluber:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CluberPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CluberPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCluber:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCluber:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CluberPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCluber:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CluberPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aNivells !== null) {
				if ($this->aNivells->isModified() || $this->aNivells->isNew()) {
					$affectedRows += $this->aNivells->save($con);
				}
				$this->setNivells($this->aNivells);
			}

			if ($this->aEntitats !== null) {
				if ($this->aEntitats->isModified() || $this->aEntitats->isNew()) {
					$affectedRows += $this->aEntitats->save($con);
				}
				$this->setEntitats($this->aEntitats);
			}

			if ($this->aUsuaris !== null) {
				if ($this->aUsuaris->isModified() || $this->aUsuaris->isNew()) {
					$affectedRows += $this->aUsuaris->save($con);
				}
				$this->setUsuaris($this->aUsuaris);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CluberPeer::IDCLUBBER;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CluberPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdclubber($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CluberPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAgendaactivitatss !== null) {
				foreach ($this->collAgendaactivitatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collBlogarticless !== null) {
				foreach ($this->collBlogarticless as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFitxerss !== null) {
				foreach ($this->collFitxerss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFitxerscomentariss !== null) {
				foreach ($this->collFitxerscomentariss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMultimedias !== null) {
				foreach ($this->collMultimedias as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aNivells !== null) {
				if (!$this->aNivells->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aNivells->getValidationFailures());
				}
			}

			if ($this->aEntitats !== null) {
				if (!$this->aEntitats->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEntitats->getValidationFailures());
				}
			}

			if ($this->aUsuaris !== null) {
				if (!$this->aUsuaris->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuaris->getValidationFailures());
				}
			}


			if (($retval = CluberPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAgendaactivitatss !== null) {
					foreach ($this->collAgendaactivitatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collBlogarticless !== null) {
					foreach ($this->collBlogarticless as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFitxerss !== null) {
					foreach ($this->collFitxerss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFitxerscomentariss !== null) {
					foreach ($this->collFitxerscomentariss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMultimedias !== null) {
					foreach ($this->collMultimedias as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CluberPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdclubber();
				break;
			case 1:
				return $this->getNivellsIdnivells();
				break;
			case 2:
				return $this->getEntitatsEntitatid();
				break;
			case 3:
				return $this->getUsuarisUsuariid();
				break;
			case 4:
				return $this->getHabilitat();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CluberPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdclubber(),
			$keys[1] => $this->getNivellsIdnivells(),
			$keys[2] => $this->getEntitatsEntitatid(),
			$keys[3] => $this->getUsuarisUsuariid(),
			$keys[4] => $this->getHabilitat(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CluberPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdclubber($value);
				break;
			case 1:
				$this->setNivellsIdnivells($value);
				break;
			case 2:
				$this->setEntitatsEntitatid($value);
				break;
			case 3:
				$this->setUsuarisUsuariid($value);
				break;
			case 4:
				$this->setHabilitat($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CluberPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdclubber($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNivellsIdnivells($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setEntitatsEntitatid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUsuarisUsuariid($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setHabilitat($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CluberPeer::DATABASE_NAME);

		if ($this->isColumnModified(CluberPeer::IDCLUBBER)) $criteria->add(CluberPeer::IDCLUBBER, $this->idclubber);
		if ($this->isColumnModified(CluberPeer::NIVELLS_IDNIVELLS)) $criteria->add(CluberPeer::NIVELLS_IDNIVELLS, $this->nivells_idnivells);
		if ($this->isColumnModified(CluberPeer::ENTITATS_ENTITATID)) $criteria->add(CluberPeer::ENTITATS_ENTITATID, $this->entitats_entitatid);
		if ($this->isColumnModified(CluberPeer::USUARIS_USUARIID)) $criteria->add(CluberPeer::USUARIS_USUARIID, $this->usuaris_usuariid);
		if ($this->isColumnModified(CluberPeer::HABILITAT)) $criteria->add(CluberPeer::HABILITAT, $this->habilitat);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CluberPeer::DATABASE_NAME);

		$criteria->add(CluberPeer::IDCLUBBER, $this->idclubber);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdclubber();
	}

	/**
	 * Generic method to set the primary key (idclubber column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdclubber($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Cluber (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNivellsIdnivells($this->nivells_idnivells);

		$copyObj->setEntitatsEntitatid($this->entitats_entitatid);

		$copyObj->setUsuarisUsuariid($this->usuaris_usuariid);

		$copyObj->setHabilitat($this->habilitat);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAgendaactivitatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgendaactivitats($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getBlogarticless() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBlogarticles($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFitxerss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFitxers($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFitxerscomentariss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFitxerscomentaris($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMultimedias() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMultimedia($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdclubber(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Cluber Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CluberPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CluberPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Nivells object.
	 *
	 * @param      Nivells $v
	 * @return     Cluber The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setNivells(Nivells $v = null)
	{
		if ($v === null) {
			$this->setNivellsIdnivells(NULL);
		} else {
			$this->setNivellsIdnivells($v->getIdnivells());
		}

		$this->aNivells = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Nivells object, it will not be re-added.
		if ($v !== null) {
			$v->addCluber($this);
		}

		return $this;
	}


	/**
	 * Get the associated Nivells object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Nivells The associated Nivells object.
	 * @throws     PropelException
	 */
	public function getNivells(PropelPDO $con = null)
	{
		if ($this->aNivells === null && ($this->nivells_idnivells !== null)) {
			$c = new Criteria(NivellsPeer::DATABASE_NAME);
			$c->add(NivellsPeer::IDNIVELLS, $this->nivells_idnivells);
			$this->aNivells = NivellsPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aNivells->addClubers($this);
			 */
		}
		return $this->aNivells;
	}

	/**
	 * Declares an association between this object and a Entitats object.
	 *
	 * @param      Entitats $v
	 * @return     Cluber The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEntitats(Entitats $v = null)
	{
		if ($v === null) {
			$this->setEntitatsEntitatid(NULL);
		} else {
			$this->setEntitatsEntitatid($v->getEntitatid());
		}

		$this->aEntitats = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Entitats object, it will not be re-added.
		if ($v !== null) {
			$v->addCluber($this);
		}

		return $this;
	}


	/**
	 * Get the associated Entitats object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Entitats The associated Entitats object.
	 * @throws     PropelException
	 */
	public function getEntitats(PropelPDO $con = null)
	{
		if ($this->aEntitats === null && ($this->entitats_entitatid !== null)) {
			$c = new Criteria(EntitatsPeer::DATABASE_NAME);
			$c->add(EntitatsPeer::ENTITATID, $this->entitats_entitatid);
			$this->aEntitats = EntitatsPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEntitats->addClubers($this);
			 */
		}
		return $this->aEntitats;
	}

	/**
	 * Declares an association between this object and a Usuaris object.
	 *
	 * @param      Usuaris $v
	 * @return     Cluber The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuaris(Usuaris $v = null)
	{
		if ($v === null) {
			$this->setUsuarisUsuariid(NULL);
		} else {
			$this->setUsuarisUsuariid($v->getUsuariid());
		}

		$this->aUsuaris = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuaris object, it will not be re-added.
		if ($v !== null) {
			$v->addCluber($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuaris object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuaris The associated Usuaris object.
	 * @throws     PropelException
	 */
	public function getUsuaris(PropelPDO $con = null)
	{
		if ($this->aUsuaris === null && ($this->usuaris_usuariid !== null)) {
			$c = new Criteria(UsuarisPeer::DATABASE_NAME);
			$c->add(UsuarisPeer::USUARIID, $this->usuaris_usuariid);
			$this->aUsuaris = UsuarisPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuaris->addClubers($this);
			 */
		}
		return $this->aUsuaris;
	}

	/**
	 * Clears out the collAgendaactivitatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgendaactivitatss()
	 */
	public function clearAgendaactivitatss()
	{
		$this->collAgendaactivitatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgendaactivitatss collection (array).
	 *
	 * By default this just sets the collAgendaactivitatss collection to an empty array (like clearcollAgendaactivitatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgendaactivitatss()
	{
		$this->collAgendaactivitatss = array();
	}

	/**
	 * Gets an array of Agendaactivitats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cluber has previously been saved, it will retrieve
	 * related Agendaactivitatss from storage. If this Cluber is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Agendaactivitats[]
	 * @throws     PropelException
	 */
	public function getAgendaactivitatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgendaactivitatss === null) {
			if ($this->isNew()) {
			   $this->collAgendaactivitatss = array();
			} else {

				$criteria->add(AgendaactivitatsPeer::CLUBER_IDCLUBBER, $this->idclubber);

				AgendaactivitatsPeer::addSelectColumns($criteria);
				$this->collAgendaactivitatss = AgendaactivitatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgendaactivitatsPeer::CLUBER_IDCLUBBER, $this->idclubber);

				AgendaactivitatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastAgendaactivitatsCriteria) || !$this->lastAgendaactivitatsCriteria->equals($criteria)) {
					$this->collAgendaactivitatss = AgendaactivitatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgendaactivitatsCriteria = $criteria;
		return $this->collAgendaactivitatss;
	}

	/**
	 * Returns the number of related Agendaactivitats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Agendaactivitats objects.
	 * @throws     PropelException
	 */
	public function countAgendaactivitatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgendaactivitatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgendaactivitatsPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$count = AgendaactivitatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgendaactivitatsPeer::CLUBER_IDCLUBBER, $this->idclubber);

				if (!isset($this->lastAgendaactivitatsCriteria) || !$this->lastAgendaactivitatsCriteria->equals($criteria)) {
					$count = AgendaactivitatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgendaactivitatss);
				}
			} else {
				$count = count($this->collAgendaactivitatss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Agendaactivitats object to this object
	 * through the Agendaactivitats foreign key attribute.
	 *
	 * @param      Agendaactivitats $l Agendaactivitats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgendaactivitats(Agendaactivitats $l)
	{
		if ($this->collAgendaactivitatss === null) {
			$this->initAgendaactivitatss();
		}
		if (!in_array($l, $this->collAgendaactivitatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgendaactivitatss, $l);
			$l->setCluber($this);
		}
	}

	/**
	 * Clears out the collBlogarticless collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBlogarticless()
	 */
	public function clearBlogarticless()
	{
		$this->collBlogarticless = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBlogarticless collection (array).
	 *
	 * By default this just sets the collBlogarticless collection to an empty array (like clearcollBlogarticless());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBlogarticless()
	{
		$this->collBlogarticless = array();
	}

	/**
	 * Gets an array of Blogarticles objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cluber has previously been saved, it will retrieve
	 * related Blogarticless from storage. If this Cluber is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Blogarticles[]
	 * @throws     PropelException
	 */
	public function getBlogarticless($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBlogarticless === null) {
			if ($this->isNew()) {
			   $this->collBlogarticless = array();
			} else {

				$criteria->add(BlogarticlesPeer::CLUBER_IDCLUBBER, $this->idclubber);

				BlogarticlesPeer::addSelectColumns($criteria);
				$this->collBlogarticless = BlogarticlesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BlogarticlesPeer::CLUBER_IDCLUBBER, $this->idclubber);

				BlogarticlesPeer::addSelectColumns($criteria);
				if (!isset($this->lastBlogarticlesCriteria) || !$this->lastBlogarticlesCriteria->equals($criteria)) {
					$this->collBlogarticless = BlogarticlesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBlogarticlesCriteria = $criteria;
		return $this->collBlogarticless;
	}

	/**
	 * Returns the number of related Blogarticles objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Blogarticles objects.
	 * @throws     PropelException
	 */
	public function countBlogarticless(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBlogarticless === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BlogarticlesPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$count = BlogarticlesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BlogarticlesPeer::CLUBER_IDCLUBBER, $this->idclubber);

				if (!isset($this->lastBlogarticlesCriteria) || !$this->lastBlogarticlesCriteria->equals($criteria)) {
					$count = BlogarticlesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collBlogarticless);
				}
			} else {
				$count = count($this->collBlogarticless);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Blogarticles object to this object
	 * through the Blogarticles foreign key attribute.
	 *
	 * @param      Blogarticles $l Blogarticles
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBlogarticles(Blogarticles $l)
	{
		if ($this->collBlogarticless === null) {
			$this->initBlogarticless();
		}
		if (!in_array($l, $this->collBlogarticless, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBlogarticless, $l);
			$l->setCluber($this);
		}
	}

	/**
	 * Clears out the collFitxerss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFitxerss()
	 */
	public function clearFitxerss()
	{
		$this->collFitxerss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFitxerss collection (array).
	 *
	 * By default this just sets the collFitxerss collection to an empty array (like clearcollFitxerss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFitxerss()
	{
		$this->collFitxerss = array();
	}

	/**
	 * Gets an array of Fitxers objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cluber has previously been saved, it will retrieve
	 * related Fitxerss from storage. If this Cluber is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Fitxers[]
	 * @throws     PropelException
	 */
	public function getFitxerss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFitxerss === null) {
			if ($this->isNew()) {
			   $this->collFitxerss = array();
			} else {

				$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

				FitxersPeer::addSelectColumns($criteria);
				$this->collFitxerss = FitxersPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

				FitxersPeer::addSelectColumns($criteria);
				if (!isset($this->lastFitxersCriteria) || !$this->lastFitxersCriteria->equals($criteria)) {
					$this->collFitxerss = FitxersPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFitxersCriteria = $criteria;
		return $this->collFitxerss;
	}

	/**
	 * Returns the number of related Fitxers objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Fitxers objects.
	 * @throws     PropelException
	 */
	public function countFitxerss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFitxerss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$count = FitxersPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

				if (!isset($this->lastFitxersCriteria) || !$this->lastFitxersCriteria->equals($criteria)) {
					$count = FitxersPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFitxerss);
				}
			} else {
				$count = count($this->collFitxerss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Fitxers object to this object
	 * through the Fitxers foreign key attribute.
	 *
	 * @param      Fitxers $l Fitxers
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFitxers(Fitxers $l)
	{
		if ($this->collFitxerss === null) {
			$this->initFitxerss();
		}
		if (!in_array($l, $this->collFitxerss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFitxerss, $l);
			$l->setCluber($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Cluber is new, it will return
	 * an empty collection; or if this Cluber has previously
	 * been saved, it will retrieve related Fitxerss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Cluber.
	 */
	public function getFitxerssJoinMultimedia($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFitxerss === null) {
			if ($this->isNew()) {
				$this->collFitxerss = array();
			} else {

				$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$this->collFitxerss = FitxersPeer::doSelectJoinMultimedia($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FitxersPeer::CLUBER_IDCLUBBER, $this->idclubber);

			if (!isset($this->lastFitxersCriteria) || !$this->lastFitxersCriteria->equals($criteria)) {
				$this->collFitxerss = FitxersPeer::doSelectJoinMultimedia($criteria, $con, $join_behavior);
			}
		}
		$this->lastFitxersCriteria = $criteria;

		return $this->collFitxerss;
	}

	/**
	 * Clears out the collFitxerscomentariss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFitxerscomentariss()
	 */
	public function clearFitxerscomentariss()
	{
		$this->collFitxerscomentariss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFitxerscomentariss collection (array).
	 *
	 * By default this just sets the collFitxerscomentariss collection to an empty array (like clearcollFitxerscomentariss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFitxerscomentariss()
	{
		$this->collFitxerscomentariss = array();
	}

	/**
	 * Gets an array of Fitxerscomentaris objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cluber has previously been saved, it will retrieve
	 * related Fitxerscomentariss from storage. If this Cluber is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Fitxerscomentaris[]
	 * @throws     PropelException
	 */
	public function getFitxerscomentariss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFitxerscomentariss === null) {
			if ($this->isNew()) {
			   $this->collFitxerscomentariss = array();
			} else {

				$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

				FitxerscomentarisPeer::addSelectColumns($criteria);
				$this->collFitxerscomentariss = FitxerscomentarisPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

				FitxerscomentarisPeer::addSelectColumns($criteria);
				if (!isset($this->lastFitxerscomentarisCriteria) || !$this->lastFitxerscomentarisCriteria->equals($criteria)) {
					$this->collFitxerscomentariss = FitxerscomentarisPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFitxerscomentarisCriteria = $criteria;
		return $this->collFitxerscomentariss;
	}

	/**
	 * Returns the number of related Fitxerscomentaris objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Fitxerscomentaris objects.
	 * @throws     PropelException
	 */
	public function countFitxerscomentariss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFitxerscomentariss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$count = FitxerscomentarisPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

				if (!isset($this->lastFitxerscomentarisCriteria) || !$this->lastFitxerscomentarisCriteria->equals($criteria)) {
					$count = FitxerscomentarisPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFitxerscomentariss);
				}
			} else {
				$count = count($this->collFitxerscomentariss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Fitxerscomentaris object to this object
	 * through the Fitxerscomentaris foreign key attribute.
	 *
	 * @param      Fitxerscomentaris $l Fitxerscomentaris
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFitxerscomentaris(Fitxerscomentaris $l)
	{
		if ($this->collFitxerscomentariss === null) {
			$this->initFitxerscomentariss();
		}
		if (!in_array($l, $this->collFitxerscomentariss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFitxerscomentariss, $l);
			$l->setCluber($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Cluber is new, it will return
	 * an empty collection; or if this Cluber has previously
	 * been saved, it will retrieve related Fitxerscomentariss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Cluber.
	 */
	public function getFitxerscomentarissJoinFitxers($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFitxerscomentariss === null) {
			if ($this->isNew()) {
				$this->collFitxerscomentariss = array();
			} else {

				$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$this->collFitxerscomentariss = FitxerscomentarisPeer::doSelectJoinFitxers($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FitxerscomentarisPeer::CLUBER_IDCLUBBER, $this->idclubber);

			if (!isset($this->lastFitxerscomentarisCriteria) || !$this->lastFitxerscomentarisCriteria->equals($criteria)) {
				$this->collFitxerscomentariss = FitxerscomentarisPeer::doSelectJoinFitxers($criteria, $con, $join_behavior);
			}
		}
		$this->lastFitxerscomentarisCriteria = $criteria;

		return $this->collFitxerscomentariss;
	}

	/**
	 * Clears out the collMultimedias collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMultimedias()
	 */
	public function clearMultimedias()
	{
		$this->collMultimedias = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMultimedias collection (array).
	 *
	 * By default this just sets the collMultimedias collection to an empty array (like clearcollMultimedias());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMultimedias()
	{
		$this->collMultimedias = array();
	}

	/**
	 * Gets an array of Multimedia objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cluber has previously been saved, it will retrieve
	 * related Multimedias from storage. If this Cluber is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Multimedia[]
	 * @throws     PropelException
	 */
	public function getMultimedias($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMultimedias === null) {
			if ($this->isNew()) {
			   $this->collMultimedias = array();
			} else {

				$criteria->add(MultimediaPeer::CLUBER_IDCLUBBER, $this->idclubber);

				MultimediaPeer::addSelectColumns($criteria);
				$this->collMultimedias = MultimediaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MultimediaPeer::CLUBER_IDCLUBBER, $this->idclubber);

				MultimediaPeer::addSelectColumns($criteria);
				if (!isset($this->lastMultimediaCriteria) || !$this->lastMultimediaCriteria->equals($criteria)) {
					$this->collMultimedias = MultimediaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMultimediaCriteria = $criteria;
		return $this->collMultimedias;
	}

	/**
	 * Returns the number of related Multimedia objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Multimedia objects.
	 * @throws     PropelException
	 */
	public function countMultimedias(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CluberPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMultimedias === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MultimediaPeer::CLUBER_IDCLUBBER, $this->idclubber);

				$count = MultimediaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MultimediaPeer::CLUBER_IDCLUBBER, $this->idclubber);

				if (!isset($this->lastMultimediaCriteria) || !$this->lastMultimediaCriteria->equals($criteria)) {
					$count = MultimediaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMultimedias);
				}
			} else {
				$count = count($this->collMultimedias);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Multimedia object to this object
	 * through the Multimedia foreign key attribute.
	 *
	 * @param      Multimedia $l Multimedia
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMultimedia(Multimedia $l)
	{
		if ($this->collMultimedias === null) {
			$this->initMultimedias();
		}
		if (!in_array($l, $this->collMultimedias, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMultimedias, $l);
			$l->setCluber($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAgendaactivitatss) {
				foreach ((array) $this->collAgendaactivitatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collBlogarticless) {
				foreach ((array) $this->collBlogarticless as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFitxerss) {
				foreach ((array) $this->collFitxerss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFitxerscomentariss) {
				foreach ((array) $this->collFitxerscomentariss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMultimedias) {
				foreach ((array) $this->collMultimedias as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAgendaactivitatss = null;
		$this->collBlogarticless = null;
		$this->collFitxerss = null;
		$this->collFitxerscomentariss = null;
		$this->collMultimedias = null;
			$this->aNivells = null;
			$this->aEntitats = null;
			$this->aUsuaris = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCluber:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCluber::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCluber
