autoload:
  facebook:
    path:      %SF_LIB_DIR%/vendor/facebook
    recursive: on
  barcode:
    path:      %SF_LIB_DIR%/vendor/barcode
    recursive: on    
  dompdf:
    path:      %SF_LIB_DIR%/vendor/dompdf
    recursive: on    