<?php

require 'lib/model/om/BaseDescomptes.php';


/**
 * Skeleton subclass for representing a row from the 'descomptes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/30/12 12:18:36
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Descomptes extends BaseDescomptes {

	/**
	 * Initializes internal state of Descomptes object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

    public function setInactiu(){
        $this->setActiu(false);
        $this->save();
    }

} // Descomptes
