<?php

require 'lib/model/om/BaseEntradesReservaPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'entrades_reserva' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/27/11 14:57:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EntradesReservaPeer extends BaseEntradesReservaPeer {
        
    const ESTAT_ENTRADA_CONFIRMADA = 10;
    const ESTAT_ENTRADA_ANULADA = 20;
    const ESTAT_ENTRADA_EN_ESPERA = 30;
    const ESTAT_ENTRADA_EN_PROCES = 40;
    const ESTAT_ENTRADA_RESERVADA = 50;
    const ESTAT_ENTRADA_ERROR = -1;

    const PAGAMENT_RESERVA = 0;
    const PAGAMENT_METALIC = 1;
    const PAGAMENT_TARGETA = 2;     


    /**
     * Retorna els tipus de venta, segons el marcat a l'entrada. 
     * */
    static public function getTipusPagaments($IDA, $IDH){
        $OEP = EntradesPreusPeer::retrieveByPK( $IDH , $IDA );                
        $A = array();                        
        
        if($OEP->getTipus() == EntradesPreusPeer::TIPUS_RESERVA): 
            $A = array( self::PAGAMENT_RESERVA => 'Només reserva' );
        elseif($OEP->getTipus() == EntradesPreusPeer::TIPUS_VENTA):
            $A = array( self::PAGAMENT_TARGETA => 'Targeta de crèdit' , self::PAGAMENT_METALIC => 'En metàl·lic' , self::PAGAMENT_RESERVA => 'Només reserva' );
        else: 
            $A = array( self::PAGAMENT_RESERVA => 'Només reserva' );
        endif; 
                
        return $A;
    }


    /**
     * @return -1 (OH incorrecte)
     * @return -2 (OA incorrecte)
     * @return -3 (OEP incorrecte)
     * @return -4 (Repe)
     * @return -5 (Exhaurides)
     * @return -6 (Error TPV)
     * @return 1 (Reserva OK)
     * @return 2 (Compra OK)
     * */
    static public function setCompraEntrada($IDH, $IDU, $NEntrades, $Descompte, $COMPRA = false)
    {
            
        //Carreguem l'activitat en qüestió per carregar les dades.
        $OH = HorarisPeer::retrieveByPK($IDH);
        if(!($OH instanceof Horaris)) return -1;
        $IDA = $OH->getActivitatsActivitatid(); 
        
        $OA = ActivitatsPeer::retrieveByPK($IDA);        
        if(!($OA instanceof Activitats)) return -2;
        
        $OEP = EntradesPreusPeer::getByActivitatOHorari($IDA, $IDH);
        if(!($OEP instanceof EntradesPreus)) return -3; //HORARI_INEXISTENT
        
        
        //Tenim un horari carregat i una activitat. 
        $idS = $OA->getSiteid();
        
        $HaComprat = EntradesReservaPeer::ExisteixenEntradesComprades($IDU, $IDH);
        $PlacesLliures = EntradesReservaPeer::countEntradesActivitatConf($IDH);
        $Tipus = ($COMPRA)?EntradesPreusPeer::TIPUS_VENTA:EntradesPreusPeer::TIPUS_RESERVA;                        
                            
        if($HaComprat) return -4; //ENTRADA_REPE
        if(($PlacesLliures - $this->NEntrades) <= 0) return -5; //NO_QUEDEN_PROU_ENTRADES                                                      
                                                        
        //Generem la nova compra o reserva
        $OER = EntradesReservaPeer::initialize( $idS , '' , 0 , $IDA , $IDH , $IDU , $NEntrades , $Tipus , $Descompte )->getObject();
            
        //Si és reserva                    
        if( $Tipus == EntradesPreusPeer::TIPUS_RESERVA ){
        
            $OER->setEstat(EntradesReservaPeer::ESTAT_ENTRADA_CONFIRMADA);                                            
            $OER->save();
         
        } elseif($Tipus == EntradesPreusPeer::TIPUS_VENTA) {
        
            $OER->setEstat(EntradesReservaPeer::ESTAT_ENTRADA_EN_ESPERA);
            $OER->save();            
                                            
        }
               
        UsuarisPeer::addSite($IDU,$idS);
        return $OER;                                                                         
        
    } 
    
    static public function getCriteriaActiu($C)
    {
        $C->add(self::ACTIU, true);
        return $C;
    }

    static public function getEstatToString($estat)
    {
        switch($estat){
            case self::ESTAT_ENTRADA_CONFIRMADA: return 'Pagada'; break;
            case self::ESTAT_ENTRADA_ANULADA: return 'Anul·lada'; break;
            case self::ESTAT_ENTRADA_EN_ESPERA: return 'En espera'; break;
            case self::ESTAT_ENTRADA_EN_PROCES: return 'En procès'; break;
            case self::ESTAT_ENTRADA_RESERVADA: return 'Reservada'; break;
            case self::ESTAT_ENTRADA_ERROR: return 'Error'; break; 
        }
    }

    static public function selectEstats(){
        return array(
            self::ESTAT_ENTRADA_EN_ESPERA => self::getEstatToString(self::ESTAT_ENTRADA_EN_ESPERA),            
            self::ESTAT_ENTRADA_CONFIRMADA => self::getEstatToString(self::ESTAT_ENTRADA_CONFIRMADA),
            self::ESTAT_ENTRADA_ANULADA => self::getEstatToString(self::ESTAT_ENTRADA_ANULADA), 
            self::ESTAT_ENTRADA_RESERVADA => self::getEstatToString(self::ESTAT_ENTRADA_RESERVADA),       
        );
        
    }

	static public function initialize( $idS , $url_ajax_usuaris, $idER , $idA , $idH , $idU = 0 , $quantitat = 0 , $tipus = EntradesPreusPeer::TIPUS_RESERVA , $Descompte = 0 )
	{				
        $OER = self::retrieveByPK($idER);
        
		if(!($OER instanceof EntradesReserva)):
			$OER = new EntradesReserva();
            $OER->setEntradesPreusActivitatId(($idA == 0)?null:$idA);
            $OER->setEntradesPreusHorariId(($idH == 0)?null:$idH);
			$OER->setUsuariid(($idU == 0)?null:$idU);
            $OER->setNomReserva(null);
            $OER->setEmailReserva(null);
            $OER->setTelefonReserva(null);
            $OER->setQuantitat($quantitat);			
			$OER->setEstat(self::ESTAT_ENTRADA_EN_ESPERA);
            $OER->setActiu(true);
            $OER->setTipus($tipus);
            $OER->setDescompte($Descompte);
            $OER->setSiteid($idS);
			$OER->setData(date('Y-m-d H:i',time()));
		endif; 		

        return new EntradesReservaForm($OER,array('ajax'=>$url_ajax_usuaris, 'IDA'=> $idA , 'IDH' => $idH ));
	}

    /**
     * Retorna per quins horaris, l'usuari ha comprat entrades
     * */
    static public function h_getEntradesUsuariArray($idU){
        $RET = array();
        
        foreach(self::getEntradesUsuari($idU) as $OER):
            $RET[$OER->getEntradesPreusHorariId()] = $OER->getIdentrada();
        endforeach;
        
        return $RET;
    }

    /**
     * Retorna per quins horaris, l'usuari ha comprat entrades
     * */
    static public function h_getEntradesActivitatUsuariArray($idU){
        $RET = array();
        
        foreach(self::getEntradesUsuari($idU) as $OER):
            $RET[$OER->getIdentrada()] = $OER->getIdentrada();
        endforeach;
        
        return $RET;
    }    

    /**
     * Retorna les entrades guardades per a un usuari en concret.
     * @param $idU Usuariid()
     * @return Llistat d'entrades
     * */
    static public function getEntradesUsuari($idU){
        $C = new Criteria();
        $C = self::getCriteriaActiu($C);        
        $C->add(self::USUARI_ID, $idU);
        
        $C->addDescendingOrderByColumn(self::IDENTRADA);
        return self::doSelect($C);        
    }

    static public function criteriaEntradesOK($C)
    {
        $C1 = $C->getNewCriterion(self::ESTAT , self::ESTAT_ENTRADA_CONFIRMADA);
        $C2 = $C->getNewCriterion(self::ESTAT , self::ESTAT_ENTRADA_RESERVADA);
        $C1->addOr($C2); $C->add($C1);
        return $C;
    }

    static public function getEntradesVenudes($idA, $idH, $nomesOK = false)
    {
        $C = new Criteria();
        $C->add(self::ENTRADES_PREUS_ACTIVITAT_ID, $idA);
        $C->add(self::ENTRADES_PREUS_HORARI_ID, $idH);
        $C->add(self::ACTIU, true);
        if($nomesOK) $C = self::criteriaEntradesOK($C);
        
        return self::doSelect($C);
    }

    /**
     * Retorna les places lliures en un horari determinat
     * @param $idH Horariid     
     * @return Int Quantes entrades queden lliures.
     * */
    static public function countEntradesActivitatConf($idH){
        $RET = 0;
        
        $C = new Criteria();
        $C = self::getCriteriaActiu($C);
        $C->add( self::ENTRADES_PREUS_HORARI_ID , $idH );         
        $C = self::criteriaEntradesOK($C);
        
        foreach(self::doSelect($C) as $OE):
            $RET += $OE->getQuantes();
        endforeach;
        
        $OEP = EntradesPreusPeer::getByActivitatOHorari(0,$idH);
        return $OEP->getPlaces() - $RET;
                
    }


    /**
     * L'usuari ja ha comprat entrades per aquest dia en concret.
     * @param $idU Usuari ID
     * @param $idH Horari ID
     * @return Int Quantes entrades s'han trobat.
     * */
    static public function ExisteixenEntradesComprades($idU,$idH)
    {
        $C = new Criteria();
        $C = self::getCriteriaActiu($C);
        
        $C->add(self::USUARI_ID, $idU);
        $C->add(self::ENTRADES_PREUS_HORARI_ID, $idH);
        $C->add(self::ESTAT,self::ESTAT_ENTRADA_ANULADA, CRITERIA::NOT_EQUAL);
        return (self::doCount($C)>0);        
    }

} // EntradesReservaPeer
