<?php

require 'lib/model/om/BaseEntradesPreusPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'entrades_preus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/03/11 11:52:23
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EntradesPreusPeer extends BaseEntradesPreusPeer {

    const MODE_HORARI = 0;
    const MODE_ACTIVITAT = 1;
    
    const TIPUS_DESACTIVAT = 0;
    const TIPUS_RESERVA = 1;
    const TIPUS_VENTA = 2;    

    static public function getEntradesHorarisByActivitat($idA){
        
        $C = new Criteria();
        $C->add(self::ACTIVITAT_ID, $idA);
        $C->addJoin(self::HORARI_ID, HorarisPeer::HORARISID);
        $C->add(self::ACTIU, true);
        $C->add(self::ACTIVITAT_ID, self::HORARI_ID, CRITERIA::NOT_EQUAL); //Agafem els que només són horaris ( tenen activitat != horari )
        $C->add(HorarisPeer::ACTIU, true);
   
        return HorarisPeer::doSelect($C);
                
    }

} // EntradesPreusPeer