<?php

require 'lib/model/om/BaseGestioMenusPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'gestio_menus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/13/10 13:08:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class GestioMenusPeer extends BaseGestioMenusPeer {

    static public function getMenusUsuari($idU,$idS)
    {
        $C = new Criteria();
        $C->addJoin(UsuarisMenusPeer::MENU_ID,self::MENU_ID);
        $C->add(UsuarisMenusPeer::USUARI_ID, $idU);
        $C->add(UsuarisMenusPeer::SITE_ID, $idS);
        $C->add(self::ACTIU, 1);
        $C->addAscendingOrderByColumn(self::ORDRE);
        $LOM = self::doSelect($C);
        return $LOM;                
    }

} // GestioMenusPeer
