<?php

require 'lib/model/om/BaseLlistesLlistesEmails.php';


/**
 * Skeleton subclass for representing a row from the 'llistes_llistes_emails' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/25/11 13:08:49
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LlistesLlistesEmails extends BaseLlistesLlistesEmails {

	/**
	 * Initializes internal state of LlistesLlistesEmails object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // LlistesLlistesEmails
