<?php

require 'lib/model/om/BaseSitesPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'sites' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/13/10 11:26:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SitesPeer extends BaseSitesPeer {
    
    static public function getCriteriaActiu( $C )
    {
      $C->add(self::ACTIU,true);      
      return $C;
    }    
    
    static public function initialize( $idS )
    {
        $OO = self::retrieveByPK($idS);            
        if(!($OO instanceof Sites)):                                    		
        	$OO = new Sites();       
            $OO->setNom('');
            $OO->setActiu(true);     		            			    			    			        			
        endif;
         
       	return new SitesForm($OO,array('IDS'=>$idS));
    }

    static public function getSelect()
    {
        $RET = array();
        $C = new Criteria();
        $C = self::getCriteriaActiu($C);
        $RET[''] = 'Nou site...';
        foreach(self::doSelect($C) as $OS):
            $RET[$OS->getSiteId()] = $OS->getNom();
        endforeach;
        return $RET;
    }
    
} // SitesPeer
