<?php

require 'lib/model/om/BaseUsuarisMenusPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'usuaris_menus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/13/10 13:08:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsuarisMenusPeer extends BaseUsuarisMenusPeer {

} // UsuarisMenusPeer
