<?php

require 'lib/model/om/BaseUsuarisSitesPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'usuaris_sites' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/13/10 11:47:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsuarisSitesPeer extends BaseUsuarisSitesPeer {
    
    static public function getFirstSite($U)
    {
        $C = new Criteria();
        $C->add(self::USUARI_ID, $U->getusuariid());
        $C->add(self::ACTIU , 1);        
        $OS = self::doSelectOne($C);        
        
        if($OS instanceof UsuarisSites):
            return $OS->getSiteId();
        else:
            return null;
        endif;
                
    }

    static public function getSitesArray($idU)
    {        
        $C = new Criteria();
        $C->add(self::USUARI_ID, $idU);
        $C->add(self::ACTIU , 1);
        $OS = self::doSelect($C);
        $RET = array();
        
        foreach($OS as $O):
            $RET[$O->getSiteId()] = $O->getSites()->getNom();
        endforeach;        
        
        return $RET;        
    }

} // UsuarisSitesPeer
