default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, gestio.css, smoothness/jquery-ui-1.7.1.custom.css]

  javascripts:    [jquery-1.3.2.min.js, jquery-ui/js/jquery-ui-1.7.1.custom.min.js]

  has_layout:     on
  layout:         layout
